### ISSUE TITLE
`igraph` 1.3.0 will break unit tests

### ISSUE THREAD

**Issue by ntamas** [dscolby/spacejamr#2]
Hello,

I am writing you to let you know that `igraph` 1.3.0 will introduce a change that causes some of the `spacejamr` unit tests to fail. In particular, calling `length(g)` on an `igraph` graph `g` in earlier versions returned `10` unconditionally, which was considered a bug by many (see https://github.com/igraph/rigraph/issues/427 ). From `igraph` 1.3.0, `length(g)` will be consistent with the `[[` indexing operator; since `[[` indexes into the adjacency list of the graph, `length(g)` will return the number of vertices in the graph.

Your unit tests check whether `length(g)` is `10` and this will not be true any more from `igraph` 1.3.0. If you would like to test the number of vertices, use `vcount(g)` instead and compare it with the expected vertex count.

**Comment by dscolby** [comment]
Thanks for the heads-up!
